name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install openmpi
      run: sudo apt-get install libopenmpi-dev openmpi-bin
    - name: make
      run: make
